/**
 * Temporary alpha terms. Single source of truth for both the signup dialog and
 * the /legal page so the two can never drift apart.
 *
 * These are interim, plain-language terms for a pre-release test build — not a
 * finished commercial agreement. Replace them with lawyer-reviewed terms before
 * PersonAIs takes payments or leaves alpha.
 */

export const TERMS_VERSION = "alpha-0.4.0";
export const TERMS_EFFECTIVE_DATE = "September 8, 2026";
export const TERMS_SUMMARY =
  "PersonAIs Alpha 0.4.0 is an unfinished test build. Accounts, chats and avatars can be reset without notice, and email verification is switched off for this release.";

export const TERMS_SECTIONS = [
  {
    id: "alpha-status",
    title: "1. This is a pre-release alpha",
    body: [
      "PersonAIs Alpha 0.4.0 is an experimental test build supplied for evaluation only. Features may change, break or disappear between releases, and the service may be unavailable at any time without warning.",
      "Nothing here is a promise of a finished product, of a specific feature, or of continued availability. Do not rely on PersonAIs for anything important.",
    ],
  },
  {
    id: "accounts",
    title: "2. Your account and how you sign in",
    body: [
      "You need one account per email address, and you must be old enough to agree to these terms where you live (16, or the minimum digital-consent age in your country if it is higher).",
      "You must sign in with an email address that has already been registered on this build. Entering an address that was never signed up will be rejected — it does not create an account for you. If you are new, use Create Account first, then log in with those exact details.",
      "Keep your password to yourself and do not reuse a password from another service. You are responsible for what happens under your account.",
    ],
  },
  {
    id: "verification",
    title: "3. Email verification is off during this release",
    body: [
      "Alpha 0.3.3 sent a verification link through a third-party email provider. That step has been removed for Alpha 0.4.0 — new accounts are usable immediately and no verification email is sent.",
      "Because nothing verifies the address, we cannot confirm that an account belongs to you, and there is no password-reset or account-recovery email in this release. If you forget your password or mistype your address at signup, that account cannot be recovered — register again with a fresh one.",
      "Do not sign up with an email address that is not yours. Verification will return in a later update, and unverified accounts may need to be confirmed or may be removed at that point.",
    ],
  },
  {
    id: "data",
    title: "4. Your data can be wiped",
    body: [
      "Alpha databases are reset regularly. Accounts, chat history, avatars, credit balances and settings may be deleted at any time, without notice and without backup.",
      "Reference photos you upload during setup are held in your own browser's local storage on the device you used, and are cleared when you clear site data.",
      "Do not submit anything confidential, sensitive, or that you would be upset to lose. Treat everything you put into the alpha as disposable.",
    ],
  },
  {
    id: "acceptable-use",
    title: "5. Acceptable use",
    body: [
      "Do not use PersonAIs to break the law, to harass anyone, or to produce sexual content involving minors, targeted harassment, malware, or content designed to deceive people about a real person's words or actions.",
      "Only upload a photo of yourself, or one you have clear permission to use. Do not build a digital twin of a real person without their consent.",
      "Do not attempt to overload, scrape, resell or reverse-engineer the service, or to work around usage caps or credit limits.",
    ],
  },
  {
    id: "ai-output",
    title: "6. AI output is not advice",
    body: [
      "Responses are generated by a language model. They can be inaccurate, biased or entirely made up, even when they sound confident.",
      "Output is not legal, medical, financial or professional advice of any kind. Check anything that matters against a reliable source before acting on it.",
    ],
  },
  {
    id: "limits",
    title: "7. Usage caps and credits",
    body: [
      "Free alpha accounts include a capped allowance of compute credits, currently 20 messages per cycle. Caps, credit costs and tier features are provisional and can change at any time during the alpha.",
      "Credits have no cash value, cannot be exchanged for money, and may be reset along with the rest of the database.",
    ],
  },
  {
    id: "no-warranty",
    title: "8. No warranty, and limited liability",
    body: [
      "PersonAIs Alpha is provided \"as is\" and \"as available\", with no warranties of any kind, express or implied, to the fullest extent the law allows.",
      "To the fullest extent permitted by law, we are not liable for lost data, lost profits, or any indirect or consequential loss arising from your use of the alpha. Nothing in these terms limits liability that cannot lawfully be limited.",
    ],
  },
  {
    id: "changes",
    title: "9. Changes, suspension and contact",
    body: [
      "We may change these terms, suspend accounts, or end the alpha at any time. Continuing to use the build after a change means you accept the updated terms.",
      "These are temporary terms for a test release and will be replaced by full terms of service and a privacy policy in a later update. Questions or account requests: support@personais.net.",
    ],
  },
];

/** Short bullets shown inline next to the signup checkbox. */
export const TERMS_HIGHLIGHTS = [
  "Alpha build — features and uptime are not guaranteed.",
  "Accounts, chats and avatars can be wiped without notice.",
  "No verification or recovery email this release — a forgotten password cannot be restored.",
  "You must log in with an email that has already been registered.",
];
